### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by trydofor** [trydofor/professional-razor#86]
* https://github.com/nuxt/nuxt/issues/12376
* https://github.com/nuxt/nuxt/pull/22333

**Comment by trydofor** [comment]
may be caused by eslint, see https://eslint.nuxt.com/packages/module

**Comment by Corentin7301** [comment]
Hey!
I've also this issue...

I've test to update tailwind.config but no result...

Any help?

**Comment by Corentin7301** [comment]
For me, build and preview is works, but only dev not running good

**Comment by trydofor** [comment]
> For me, build and preview is works, but only dev not running good

No progress, still trying.

**Comment by trydofor** [comment]
```log

[5:43:58 PM]  WARN  Failed to parse static properties from plugin node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.8.6_eslint@9.13.0_jiti@2.3.3__ioredis@5.4.1__mmnznmnhtfa3gabzpu4lo43haa/node_modules/nuxt/dist/app/plugins/revive-payload.server.js. spawn EBADF

  at ChildProcess.spawn (node:internal/child_process:421:11)
  at Object.spawn (node:child_process:762:9)
  at ensureServiceIsRunning (node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/lib/main.js:1980:29)
  at transform (node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/lib/main.js:1880:37)
  at extractMetadata (node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.8.6_eslint@9.13.0_jiti@2.3.3__ioredis@5.4.1__mmnznmnhtfa3gabzpu4lo43haa/node_modules/nuxt/dist/index.mjs:3838:20)
  at annotatePlugins (node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.8.6_eslint@9.13.0_jiti@2.3.3__ioredis@5.4.1__mmnznmnhtfa3gabzpu4lo43haa/node_modules/nuxt/dist/index.mjs:5421:18)
  at async getContents (node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.8.6_eslint@9.13.0_jiti@2.3.3__ioredis@5.4.1__mmnznmnhtfa3gabzpu4lo43haa/node_modules/nuxt/dist/index.mjs:4794:27)
  at async i.getContents (node_modules/.pnpm/@nuxt+devtools@1.6.0_rollup@4.24.3_vite@5.4.10_@types+node@22.8.6_terser@5.36.0__vue@3.5.12_t_heqf7i7in3lyg2zs4y2dzpwutu/node_modules/@nuxt/devtools/dist/chunks/plugin-metrics.mjs:10:23)
  at async processTemplate (node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.8.6_eslint@9.13.0_jiti@2.3.3__ioredis@5.4.1__mmnznmnhtfa3gabzpu4lo43haa/node_modules/nuxt/dist/index.mjs:5271:22)
  at async Promise.allSettled (index 2)


 ERROR  [unhandledRejection] EMFILE: too many open files, watch                                                                             5:44:02 PM

  at FSWatcher._handle.onchange (node:internal/fs/watchers:207:21)

^C *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by Corentin7301** [comment]
If it helps, I just created a docker environment and the dev server is working fine.

Here is my docker config:

**1. Dockerfile:**
```
FROM node:22.11-alpine
WORKDIR /app
RUN apk update && apk upgrade
COPY ./package*.json /app/
RUN npm install && npm cache clean --force
COPY . .
ENV PATH ./node_modules/.bin/:$PATH
```

**2. docker-compose:**
```
version: '3.3'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    tmpfs: /tmp
    command: npm run dev
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"
 ``` 
 **3. .dockerignore**
```
node_modules
.nuxt
.output
```

**Comment by notumar** [comment]
> ## Work
> * `devtools: { enabled: false },`
> 
> ## Not Work
> * rm node_modules and install
> * restart vscode
> * restart computer
> * brew install watchman
> * sudo launchctl limit maxfiles 8192 16384
> * experimental.watcher='parcel' or '@parcel/watcher'

You are a king! `devtools: { enabled: false },` worked for me finally!

**Comment by trydofor** [comment]
My guess is that the issue is due to some indirect DEPs upgrade.
and affects dev=true, may the watching of eslint, tailwind/unocss, nuxt.

the followings are changed, but tested for no effect

* node from 20.16 to 20.18
* vite-plugin-eslint2 removed

**Comment by trydofor** [comment]
💊 just do the following, all issues gone,

* prune pnpm store
* upgrade nuxt to 3.14.0

so, the reason may be some indirect Deps upgrade between these days to nuxt 3.14.

the lesson I v taken is SHOULD 

* use fixed version than range
* use lockfile first
* dont upgrade during minor release


```bash
## reset by bash
pnpm store prune
find . -name "node_modules" -type d -prune -exec rm -rf {} +
find . -name "pnpm-lock.yaml" -type f -exec rm -f {} +
asdf install
pnpm -w i --ignore-pnpmfile
pnpm i
```

**Comment by sabrinamiao** [comment]
> ## Work
> * `devtools: { enabled: false },`
> 
> ## Not Work
> * rm node_modules and install
> * restart vscode
> * restart computer
> * brew install watchman
> * sudo launchctl limit maxfiles 8192 16384
> * experimental.watcher='parcel' or '@parcel/watcher'

only devtools: {enabled: false} worked, thanks for the help!

**Comment by sabrinamiao** [comment]
I tested to reproduce the issue,  it seems only reproducable after I upgrade to nuxt 3.15.4(the latest version I get), it works without any error with nuxt 3.13.2.
